=== AMWA-TV/is-05/APIs/schemas/constraints-schema-mqtt.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Used to express the dynamic constraints on MQTT transport parameters. These constraints may be set and changed at run time. Every transport parameter must have an entry, even if it is only an empty object.",
  "patternProperties": {
    "^ext_[a-zA-Z0-9_]+$":{
      "$ref": "constraint-schema.json#/definitions/constraint"
    }
  },
  "properties": {
    "destination_host": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "source_host": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "broker_topic": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "broker_protocol": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "broker_authorization": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "connection_status_broker_topic": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "source_port": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    },
    "destination_port": {
      "$ref": "constraint-schema.json#/definitions/constraint"
    }
  }
}

=== AMWA-TV/is-05/examples/sender-constraints-get-200-mqtt.json
[{
  "destination_host": {},
  "destination_port": {
    "enum": [
      1833,
      8883
    ]
  },
  "broker_topic": {
    "enum": [
      "fixedTopicName1",
      "fixedTopicName2"
    ]
  },
  "broker_protocol": {
    "enum": [
      true,
      false
    ]
  },
  "broker_authorization": {
    "enum": [
      true,
      false
    ]
  },
  "connection_status_broker_topic": {
    "enum": [
      "connStatusTopic"
    ]
  }
}]
