=== AMWA-TV/is-05/APIs/schemas/receiver-stage-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a receiver",
  "title": "Receiver resource",
  "additionalProperties": false,
  "properties": {
    "sender_id": {
      "description": "ID of the Sender subscribed to by this Receiver. This will be null if the receiver has not been configured to receive anything, or if it is receiving from a non-NMOS sender.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "master_enable": {
      "description": "Master on/off control for receiver",
      "type": "boolean"
    },
    "activation": {
      "$ref": "activation-schema.json"
    },
    "transport_file": {
      "$ref": "receiver-transport-file.json"
    },
    "transport_params": {
      "description": "Transport-specific parameters. If this parameter is included in a client request it must include the same number of array elements (or 'legs') as specified in the constraints. If no changes are required to a specific leg it must be included as an empty object ({}).",
      "anyOf": [{
          "$ref": "receiver_transport_params_rtp.json"
        },
        {
          "$ref": "receiver_transport_params_dash.json"
        },
        {
          "$ref": "receiver_transport_params_websocket.json"
        },
        {
          "$ref": "receiver_transport_params_mqtt.json"
        }
      ]
    }
  }
}

=== AMWA-TV/is-05/examples/v1.0-receiver-patch-redundant-streams.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null
  },
  "transport_params": [{
      "interface_ip": "192.168.200.15",
      "multicast_ip": "232.105.26.177",
      "source_ip": "192.168.200.10",
      "destination_port": 5000,
      "rtp_enabled": true
    },
    {
      "interface_ip": "192.168.210.15",
      "multicast_ip": "232.3.28.144",
      "source_ip": "192.168.210.10",
      "destination_port": 5000,
      "rtp_enabled": true
    }
  ]
}

=== AMWA-TV/is-05/branches/master/examples/v1.0-receiver-patch-absolute.json
{
    "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
    "master_enable": true,
    "activation": {
        "mode": "activate_scheduled_absolute",
        "requested_time": "1496677550:20"
    },
    "transport_params": [{
        "source_ip": "172.23.19.49"
    }, {
        "source_ip": "172.23.19.49"
    }]
}

=== AMWA-TV/is-05/examples/v1.0-receiver-patch-unicast.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null
  },
  "transport_params": [{
    "interface_ip": "192.168.200.15",
    "multicast_ip": null,
    "source_ip": "192.168.200.10",
    "destination_port": 5000,
    "rtp_enabled": true
  }]
}
