=== AMWA-TV/is-05/APIs/schemas/receiver-response-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a receiver",
  "title": "Receiver resource",
  "additionalProperties": false,
  "required": [
    "sender_id",
    "master_enable",
    "activation",
    "transport_file",
    "transport_params"
  ],
  "properties": {
    "sender_id": {
      "description": "ID of the Sender subscribed to by this Receiver. This will be null if the receiver has not been configured to receive anything, or if it is receiving from a non-NMOS sender.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "master_enable": {
      "description": "Master on/off control for receiver",
      "type": "boolean"
    },
    "activation": {
      "$ref": "activation-response-schema.json"
    },
    "transport_file": {
      "$ref": "receiver-transport-file.json"
    },
    "transport_params": {
      "$ref": "receiver_transport_params.json"
    }
  }
}

=== AMWA-TV/is-05/examples/v1.0-receiver-stage-success-redundant-streams.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null,
    "activation_time": "1496739062:0"
  },
  "transport_file": {
    "data": null,
    "type": null
  },
  "transport_params": [{
    "interface_ip": "192.168.200.15",
    "multicast_ip": "232.105.26.177",
    "source_ip": "192.168.200.10",
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_mode": "2D",
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "rtcp_enabled": true,
    "rtcp_destination_ip": "232.22.4.59",
    "rtcp_destination_port": 5001,
    "rtp_enabled": true
  }, {
    "interface_ip": "192.168.200.15",
    "multicast_ip": "232.105.26.177",
    "source_ip": "192.168.200.10",
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_mode": "2D",
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "rtcp_enabled": true,
    "rtcp_destination_ip": "232.79.192.98",
    "rtcp_destination_port": 5001,
    "rtp_enabled": true
  }]
}
