=== AMWA-TV/is-05/APIs/schemas/receiver-response-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a receiver",
  "title": "Receiver resource",
  "additionalProperties": false,
  "required": [
    "sender_id",
    "master_enable",
    "activation",
    "transport_file",
    "transport_params"
  ],
  "properties": {
    "sender_id": {
      "description": "ID of the Sender subscribed to by this Receiver. This will be null if the receiver has not been configured to receive anything, or if it is receiving from a non-NMOS sender.",
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "master_enable": {
      "description": "Master on/off control for receiver",
      "type": "boolean"
    },
    "activation": {
      "$ref": "activation-response-schema.json"
    },
    "transport_file": {
      "$ref": "receiver-transport-file.json"
    },
    "transport_params": {
      "$ref": "receiver_transport_params.json"
    }
  }
}

=== AMWA-TV/is-05/examples/receiver-active-get-200.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": "1496739062:0",
    "activation_time": "1496739062:263900"
  },
  "transport_file": {
    "data": "v=0\r\no=- 1496222842 1496222842 IN IP4 172.29.226.25\r\ns=IP Studio Stream\r\nt=0 0\r\nm=video 5010 RTP/AVP 103\r\nc=IN IP4 232.250.98.80/32\r\na=source-filter:incl IN IP4 232.250.98.80 172.29.226.25\r\na=rtpmap:103 raw/90000\r\na=fmtp:103 sampling=YCbCr-4:2:2; width=1920; height=1080; depth=10; interlace=1; framerate=25; colorimetry=BT709-2\r\na=mediaclk:direct=1876655126 rate=90000\r\na=extmap:1 urn:x-nmos:rtp-hdrext:origin-timestamp\r\na=extmap:2 urn:ietf:params:rtp-hdrext:smpte-tc 3600@90000/25\r\na=extmap:3 urn:x-nmos:rtp-hdrext:flow-id\r\na=extmap:4 urn:x-nmos:rtp-hdrext:source-id\r\na=extmap:5 urn:x-nmos:rtp-hdrext:grain-flags\r\na=extmap:7 urn:x-nmos:rtp-hdrext:sync-timestamp\r\na=extmap:9 urn:x-nmos:rtp-hdrext:grain-duration\r\na=ts-refclk:ptp=IEEE1588-2008:08-00-11-FF-FE-21-E1-B0:0\r\n",
    "type": "application/sdp"
  },
  "transport_params": [{
    "source_ip": "172.29.226.25",
    "multicast_ip": "232.250.98.80",
    "interface_ip": "172.23.19.35",
    "destination_port": 5010,
    "fec_enabled": false,
    "fec_mode": "2D",
    "fec1D_destination_port": 5012,
    "fec2D_destination_port": 5014,
    "rtcp_enabled": false,
    "rtcp_destination_ip": "232.250.98.80",
    "rtcp_destination_port": 5001,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/receiver-stage-scheduled-absolute.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": "activate_scheduled_absolute",
    "requested_time": "1496739064:0",
    "activation_time": "1496739064:2500"
  },
  "transport_file": {
    "data": null,
    "type": null
  },
  "transport_params": [{
    "interface_ip": "192.168.200.15",
    "multicast_ip": "232.105.26.177",
    "source_ip": "192.168.200.10",
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_mode": "2D",
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "rtcp_enabled": true,
    "rtcp_destination_ip": "auto",
    "rtcp_destination_port": 5001,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/receiver-active-get-200-uninit.json
{
  "sender_id": null,
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_file": {
    "data": null,
    "type": null
  },
  "transport_params": [{
    "source_ip": null,
    "multicast_ip": null,
    "interface_ip": "172.23.19.35",
    "destination_port": 5004,
    "fec_enabled": false,
    "fec_destination_ip": "172.23.19.35",
    "fec1D_destination_port": 5006,
    "fec2D_destination_port": 5008,
    "rtcp_enabled": false,
    "rtcp_destination_ip": "172.23.19.35",
    "rtcp_destination_port": 5005,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/receiver-active-get-200-mqtt.json
{
  "sender_id": "eae33112-b56c-4a36-8b68-05ab5b6268bc",
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": "1541508905:0",
    "activation_time": "1541508905:263900"
  },
  "transport_file": {
    "data": null,
    "type": null
  },
  "transport_params": [{
    "source_host": "broker.mydomain.com",
    "source_port": 1883,
    "broker_topic": "my_topic_name",
    "broker_protocol": "mqtt",
    "broker_authorization": false,
    "connection_status_broker_topic": "my_status_topic_name"
  }]
}

=== AMWA-TV/is-05/tags/v1.0/examples/v1.0-receiver-stage-success.json
{
    "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
    "master_enable": true,
    "activation": {
        "mode": "activate_immediate",
        "requested_time": null,
        "activation_time": "1496739062:0"
    },
    "transport_file": {
        "data": null,
        "type": "application/sdp"
    },
    "transport_params": [{
        "source_ip": "172.23.19.48",
        "multicast_ip": "232.250.98.80",
        "interface_ip": "172.23.19.35",
        "destination_port": 5000,
        "fec_enabled": true,
         "fec_mode": "2D",
        "fec1D_destination_port": "auto",
        "fec2D_destination_port": "auto",
        "rtcp_enabled": true,
        "rtcp_destination_ip": "auto",
        "rtcp_destination_port": 5001,
        "rtp_enabled": true
    }, {
        "source_ip": "172.23.20.48",
        "multicast_ip": "232.11.105.25",
        "interface_ip": "172.23.20.35",
        "fec_enabled": true,
         "fec_mode": "2D",
        "fec1D_destination_port": "auto",
        "fec2D_destination_port": "auto",
        "rtcp_enabled": true,
        "rtcp_destination_ip": "auto",
        "rtcp_destination_port": 5001,
        "rtp_enabled": true
    }]
}

=== AMWA-TV/is-05/branches/documentation/examples/v1.0-receiver-stage-scheduled-relative.json
{
    "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
    "master_enable": true,
    "activation":{
        "mode": "activate_scheduled_relative",
        "requested_time": "2:0",
        "scheduled_time": "1496739064:0"
    },
    "transport_file":{
        "data": null,
        "type": "application/sdp"
    },
    "transport_params": [{
	"src_ip": "172.23.19.48",
	"multicast_group": "232.250.98.80",
        "interface_ip": "172.23.19.35",
	"dest_port": 5000,
        "fec_enabled": true,
	"fec_type": "XOR",
	"fec_mode": "2D",
	"fec1D_dest_port": "auto",
	"fec2D_dest_port": "auto",
        "rtcp_enabled": true,
        "rtcp_dest_ip": "auto",
	"rtcp_dest_port": 5001,
	"rtp_enabled": true
    }, {
	"src_ip": "172.23.20.48",
	"multicast_group": "232.11.105.25",
        "interface_ip": "172.23.20.35",
        "fec_enabled": true,
	"fec_type": "XOR",
	"fec_mode": "2D",
	"fec1D_dest_port": "auto",
	"fec2D_dest_port": "auto",
        "rtcp_enabled": true,
	"rtcp_dest_ip": "auto",
	"rtcp_dest_port": 5001,
	"rtp_enabled": true
    }]
}

=== AMWA-TV/is-05/examples/v1.0-receiver-get-200-uninit.json
{
  "sender_id": null,
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_file": {
    "data": null,
    "type": null
  },
  "transport_params": [{
    "source_ip": null,
    "multicast_ip": null,
    "interface_ip": "auto",
    "destination_port": "auto",
    "fec_enabled": false,
    "fec_destination_ip": "auto",
    "fec_mode": "1D",
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "rtcp_enabled": false,
    "rtcp_destination_ip": "auto",
    "rtcp_destination_port": "auto",
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/receiver-get-200.json
{
  "sender_id": "5709255c-c0ae-4e1e-99a0-e872e83e48e0",
  "master_enable": true,
  "activation": {
    "mode": null,
    "requested_time": null,
    "activation_time": null
  },
  "transport_file": {
    "data": null,
    "type": null
  },
  "transport_params": [{
    "source_ip": "172.23.19.48",
    "multicast_ip": "232.250.98.80",
    "interface_ip": "172.23.19.110",
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_destination_ip": "auto",
    "fec_mode": "2D",
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "rtcp_enabled": true,
    "rtcp_destination_ip": "auto",
    "rtcp_destination_port": 5001,
    "rtp_enabled": true
  }, {
    "source_ip": "172.23.20.48",
    "multicast_ip": "232.250.99.80",
    "interface_ip": "172.23.20.110",
    "destination_port": 5000,
    "fec_enabled": true,
    "fec_destination_ip": "auto",
    "fec_mode": "2D",
    "fec1D_destination_port": "auto",
    "fec2D_destination_port": "auto",
    "rtcp_enabled": true,
    "rtcp_destination_ip": "auto",
    "rtcp_destination_port": 5001,
    "rtp_enabled": true
  }]
}
