=== AMWA-TV/is-05/APIs/schemas/v1.0-sender-patch-success-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "Describes a sender",
    "title": "Sender resource",
    "additionalProperties": false,
    "properties": {
        "receiver_id": {
            "description": "ID of the target Receiver of this Sender (relevant for unicast only)",
            "type": [
                "string",
                "null"
            ],
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
            "default": null
        },
        "master_enable": {
            "description": "Master on/off control for receiver",
            "type": "boolean",
            "default": true
        },
        "activation":{
            "description": "Parameters concerned with activation of the transport parameters",
            "type": "object",
            "additionalProperties": false,
            "properties":{
                "mode": {
                    "description": "mode of activation: immediate (on message rx), scheduled_absolute (when internal clock >= requested_time), scheduled_relative (when internal clock >= time of message rx + requested_time), null (no activation scheduled)",
                    "type": [
                        "string",
                        "null"
                    ],
                    "enum": [
                        "activate_immediate",
                        "activate_scheduled_absolute",
                        "activate_scheduled_relative",
                        null
                    ]
                },
                "requested_time": {
                    "description": "String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating time (absolute or relative) for activation",
                    "type": [
                        "string",
                        "null"
                    ],
                    "default": null,
                    "pattern": "^[0-9]+:[0-9]+$"
                },
                "scheduled_time": {
                    "description": "String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating Time (absolute or relative) the sender will actually activate for scheduled activations, or the time acitvation occured for immediate activations.",
                    "type": [
                        "string",
                        "null"
                    ],
                    "default": null,
                    "pattern": "^[0-9]+:[0-9]+$"
                }
            }
        },
        "transport_file":{
            "type": "object",
            "description": "Transport file parameters",
            "additionalProperties": false,
            "properties":{
                "data":{
                    "description": "Content of the transport file",
                    "type": [
                        "string",
                        "null"
                    ],
                    "default": null
                },
                "type":{
                    "description": "Mime type for file (e.g application/sdp)",
                    "type": [
                        "string",
                        "null"
                    ],
                    "default": null
                }
            }
        },
        "transport_params": {
            "description": "Transport-specific parameters",
            "oneOf": [
                { "$ref": "v1.0_sender_transport_params_rtp" },
                { "$ref": "v1.0_sender_transport_params_dash" }
            ]
        }
    }
}

=== AMWA-TV/is-05/examples/v1.0-sender-patch-redundant-streams.json
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": "activate_immediate",
    "requested_time": null
  },
  "transport_params": [{
      "source_ip": "192.168.200.10",
      "destination_ip": "232.105.26.177",
      "source_port": 5000,
      "destination_port": 5000,
      "rtp_enabled": true
    },
    {
      "source_ip": "192.168.210.10",
      "destination_ip": "232.3.28.144",
      "source_port": 5000,
      "destination_port": 5000,
      "rtp_enabled": true
    }
  ]
}

=== AMWA-TV/is-05/branches/master/examples/v1.0-sender-patch.json
{
    "receiver_id": "0b174530-e3cf-41e6-bf01-fe55135034f3",
    "master_enable": true,
    "activation": {
        "mode": "activate_immediate",
        "requested_time": null
    },
    "transport_params": [{
        "rtcp_enabled": false,
        "rtcp_source_port": 5010
    },{
        "rtcp_enabled": false,
        "rtcp_source_port": 5010
    }]
}

=== AMWA-TV/is-05/examples/sender-patch-unicast.json
{
  "receiver_id": "0b174530-e3cf-41e6-bf01-fe55135034f3",
  "master_enable": true,
  "activation": {
    "mode": "activate_scheduled_relative",
    "requested_time": "2:0"
  },
  "transport_params": [{
    "source_ip": "192.168.200.10",
    "destination_ip": "192.168.200.15",
    "source_port": 5000,
    "destination_port": 5000,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/examples/v1.0-sender-patch-absolute.json
{
  "receiver_id": null,
  "master_enable": true,
  "activation": {
    "mode": "activate_scheduled_absolute",
    "requested_time": "1496759200:0"
  },
  "transport_params": [{
    "source_ip": "192.168.200.10",
    "destination_ip": "232.105.26.177",
    "source_port": 5000,
    "destination_port": 5000,
    "rtp_enabled": true
  }]
}

=== AMWA-TV/is-05/branches/master/examples/v1.0-sender-patch-absolute.json
{
    "receiver_id": "0b174530-e3cf-41e6-bf01-fe55135034f3",
    "master_enable": true,
    "activation": {
        "mode": "activate_scheduled_absolute",
        "requested_time": "1496759200:0"
    },
    "transport_params": [{
        "rtcp_enabled": false,
        "rtcp_source_port": 5010
    },{
        "rtcp_enabled": false,
        "rtcp_source_port": 5010
    }]
}

=== AMWA-TV/is-05/tags/workshop2-end/examples/v1.0-sender-patch-relative.json
{
    "receiver_id": "0b174530-e3cf-41e6-bf01-fe55135034f3",
    "master_enable": true,
    "activation": {
        "mode": "activate_scheduled_relative",
        "requested_time": "2:0"
    },
    "transport_params": [{
        "rtcp_enabled": false,
        "rtcp_source_port": 5010
    },{
        "rtcp_enabled": false,
        "rtcp_source_port": 5010
    }]
}
